### ISSUE TITLE
About page throw exception

### ISSUE THREAD

**Issue by zerg000000** [piranha/piu.clj#1]
when visit https://paste.in.ua/about/, the follow message is shown

```
No matching field found: reset for class java.io.StringReader
```

**Comment by sansolovyov** [comment]
That is because `/about/` is parsed from markdown and triggers [this issue](https://github.com/oracle/graal/issues/2561) in GraalVM. :(

**Comment by sansolovyov** [comment]
Tried to fix that and this is [the result](https://github.com/piranha/piu.clj/runs/876762368#step:7:312)

**Comment by sansolovyov** [comment]
I thought "fuck that" and switched to commonmark-java, which fixed the issue. :)
