### ISSUE TITLE
Multi-line entities break code highlighting

### ISSUE THREAD

**Issue by EXL** [piranha/piu.clj#2]
Only the first line is highlighted for multi-line comments and there are some other syntax highlighting glitches due to incorrect HTML generation.

A simple example to demonstrate the problem:

```
/*
 * Multi-line comment!
 */

<span class="comment">/*
 * Multi-line comment!
 */</span>

<tr><td>1</td><td><span class="comment">/*</td></tr>
<tr><td>2</td><td> * Multi-line comment!</td></tr>
<tr><td>3</td><td> */</span></td></tr>
```

The `<span>` tags are left unclosed inside `<td>` tags, this leads to a syntax highlighting issues.

A more complex example to demonstrate the problem: https://paste.in.ua/eyk9/

![image](https://user-images.githubusercontent.com/232116/103136972-6cbb1b00-46f7-11eb-9326-fc411e7ab28d.png)

HTML Validation Report: https://validator.w3.org/nu/?doc=https%3A%2F%2Fpaste.in.ua%2Feyk9%2F

-----

I tried to solve this problem on my similar code snippets sharing service: https://code.exlmoto.ru/161

![image](https://user-images.githubusercontent.com/232116/103137045-20bca600-46f8-11eb-9cb0-90be9d5ee1bc.png)

HTML Validation Report: https://validator.w3.org/nu/?doc=https%3A%2F%2Fcode.exlmoto.ru%2F161

My solution to this problem is described here: https://habr.com/ru/post/534044/#service

And in the source code of my project: 
https://github.com/EXL/CodePolyglot/blob/master/src/main/java/ru/exlmoto/code/highlight/filter/TagCompensator.java

-----

I hope you find this information useful.
Merry Christmas and Happy New Year!

**Comment by sansolovyov** [comment]
Hey man, I finally got to it and fixed it! It's [not exactly pretty](https://github.com/piranha/piu.clj/blob/master/src/piu/highlight.clj#L67-L89), but I just wanted it to work already. Also I guess I could skip generating closing tags since browsers are excellent at that stuff, but IDK, feel dirtier?..

**Comment by EXL** [comment]
Cool! Syntax highlighting is now error free!

>Also I guess I could skip generating closing tags since browsers are excellent at that stuff, but IDK, feel dirtier?..

Well, since Nu Html Checker from W3C shows no errors, then everything is fine. Big thanks!

**Comment by sansolovyov** [comment]
Thank you, actually! :-)
